spring:
  application:
    name: spring-security-demo
  profiles:
    active: dev

# mybatis-plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #mybatis-plus自动打开驼峰映射，mybatis则自动关闭
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1 #被删除
      logic-not-delete-value: 0 #正常
# 日志配置
logging:
  level:
    com:
      weng:
        springsecuritydemo:
          mapper: debug
          service: debug
          controller: debug


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970 #secert不能少于256bit，也就是32位字符
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
